---

vault_mariadb_passwords: "{{ lookup('community.hashi_vault.vault_kv2_get', 'sql/mariadb/passwords', engine_mount_point='secrets/infrastructure/ansible-playbooks')['secret'] }}"
vault_pterodactyl: "{{ lookup('community.hashi_vault.vault_kv2_get', 'web/pterodactyl', engine_mount_point='secrets/infrastructure/ansible-playbooks')['secret'] }}"
vault_nameless_email: "{{ lookup('community.hashi_vault.vault_kv2_get', 'web/nameless/email', engine_mount_point='secrets/infrastructure/ansible-playbooks')['secret'] }}"

dns_records:
  - zone: minersrealm.net
    record: minersrealm.net
  - zone: minersrealm.net
    record: www.minersrealm.net
  - zone: minersrealm.net
    record: panel.minersrealm.net

web_certs:
  minersrealm.net:
    cloudflare_zone: minersrealm.net
    alternative_domains:
    - panel.minersrealm.net
    - www.minersrealm.net

nameless_core_version: 2.2.4
nameless_lithium_version: 1.33
nameless_tebex_version: 1.4.0

nameless_config:
  db:
    host: sql.dylanw.net
    port: 3306
    user: miners
    password: "{{ vault_mariadb_passwords['miners'] }}"
    name: miners_website
  email: "{{ vault_nameless_email }}"

pterodactyl_env: "{{ vault_pterodactyl }}"
