execute-ansible:
  id_tokens:
    ANSIBLE_HASHI_VAULT_JWT:
      aud: https://vault.dylanw.net
  stage: deploy
  image: python:3.13.4
  script:
    # Generate a new SSH key to be used for connecting to VMs
    # This will be signed by Vault
    - ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""

    # curl and jq are used for making API request to Vault, sshpass is used by Ansible for connecting to use the 'ssh'
    # connection type with passwords
    - apt update && apt install -y curl jq sshpass

    # Use GitLab JWT token to obtain a Vault token
    - 'export VAULT_TOKEN=$(curl --request POST --data "{ \"jwt\": \"$ANSIBLE_HASHI_VAULT_JWT\", \"role\": \"gitlab\" }" "$VAULT_ADDR/v1/auth/gitlab-jwt/login" | jq -r ".auth.client_token")'

    # Ask Vault to sign our certificate
    - 'curl --header "X-Vault-Token: $VAULT_TOKEN" --request POST --data "{ \"public_key\": \"$(cat $HOME/.ssh/id_rsa.pub)\" }" "$VAULT_ADDR/v1/infrastructure/ansible-playbooks/ssh-clients/sign/ansible" | jq -r ".data.signed_key" > $HOME/.ssh/id_rsa-cert.pub'

    # Install Python requirements (including Ansible)
    - pip install -r requirements.txt

    # Install Ansible roles and collections
    - ansible-galaxy install -r requirements.yml

    # Finally, run Ansible playbook
    - ansible-playbook -i london.proxmox.yml playbooks/main.yml
