# Ansible includes some collection in the full installation!  Use versioning to prevent differences in collection
# versions on development environment and GitLab CI!

collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 12.2.0
  - name: community.crypto
    version: 3.1.0
  - name: community.dns
    version: 3.4.2
  - name: community.docker
    version: 5.0.4
  - name: community.mysql
    version: 4.0.1
  - name: community.proxmox
    version: 1.5.0
  - name: grafana.grafana
    version: 6.0.6
  - name: prometheus.prometheus
    version: 0.27.5

roles:
  - name: geerlingguy.composer
    version: 1.9.2
  - name: geerlingguy.docker
    version: 7.9.0
  - name: geerlingguy.redis
    version: 1.9.1
  - name: geerlingguy.php
    version: 6.0.0
  - name: geerlingguy.php-versions
    version: 7.0.1
  - name: mailcow.mailcow
    # The role is versionless and will always install from the master branch.
    version: master
  - name: nginxinc.nginx
    version: 0.25.0
  - name: nginxinc.nginx_config
    version: 0.7.1
