---

- name: Install prerequisite for GitLab
  ansible.builtin.package:
    name:
      - curl
      - openssh-server
      - ca-certificates
      - perl
    state: present

- name: Run script from GitLab to configure GitLab repositories
  ansible.builtin.shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | bash
  args:
    creates: /etc/apt/sources.list.d/gitlab_gitlab-ee.list

- name: Install GitLab
  ansible.builtin.package:
    name:
      - "{{ gitlab_version }}"
    state: present
  environment:
    EXTERNAL_URL: "{{ gitlab_url }}"
  register: install_gitlab

- name: Wait for 1 minute after GitLab installation
  ansible.builtin.wait_for:
    timeout: 60
  when: install_gitlab.changed

- name: Install GitLab configuration file template
  ansible.builtin.template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  register: gitlab_template_file

- name: Reconfigure GitLab
  ansible.builtin.command: gitlab-ctl reconfigure
  when: gitlab_template_file.changed

- name: Get information on initial_root_password
  ansible.builtin.stat:
    path: /etc/gitlab/initial_root_password
  register: initial_root_password_stat

- name: Get initial_root_password file contents
  ansible.builtin.shell: cat /etc/gitlab/initial_root_password
  register: initial_root_password
  when: initial_root_password_stat.stat.exists

- name: Print the initial root password, if it exists
  ansible.builtin.debug:
    msg: "{{ initial_root_password.stdout }}"
  when: initial_root_password_stat.stat.exists
