---

- name: Install AWS Roles Anywhere signing helper
  ansible.builtin.get_url:
    url: "https://rolesanywhere.amazonaws.com/releases/1.8.0/X86_64/Linux/Amzn2023/aws_signing_helper"
    dest: /usr/local/bin/aws_signing_helper
    owner: root
    group: root
    mode: '0755'
    checksum: "sha256:4ec587c4b2a7a4b2980f0fb084c3fabd99a862ce1091341ba514ae3c0923b905"

- name: Request Certificate from Vault
  community.hashi_vault.vault_pki_generate_certificate:
    engine_mount_point: "infrastructure/aws-roles-anywhere-pki"
    role_name: "backup-client"
    common_name: "{{ ansible_fqdn }}"
  register: vault_cert
  become: no
  delegate_to: localhost
  run_once: false

- name: Write Private Key to Disk
  ansible.builtin.copy:
    content: "{{ vault_cert.data.data.private_key }}"
    dest: "{{ aws_key_path }}/aws-backup.key"
    owner: "{{ aws_backup_user }}"
    group: "{{ aws_backup_group }}"
    mode: '0600'
  no_log: true

- name: Write Leaf Certificate to Disk
  ansible.builtin.copy:
    content: "{{ vault_cert.data.data.certificate }}"
    dest: "{{ aws_cert_path }}/aws-backup.crt"
    owner: "{{ aws_backup_user }}"
    group: "{{ aws_backup_group }}"
    mode: '0644'

- name: Write Intermediate Chain to Disk
  ansible.builtin.copy:
    content: "{{ vault_cert.data.data.ca_chain | join('\n') }}"
    dest: "{{ aws_cert_path }}/aws-backup-chain.pem"
    owner: "{{ aws_backup_user }}"
    group: "{{ aws_backup_group }}"
    mode: '0644'

- name: Ensure .aws directory exists
  ansible.builtin.file:
    path: "~{{ aws_backup_user }}/.aws"
    state: directory
    owner: "{{ aws_backup_user }}"
    group: "{{ aws_backup_group }}"
    mode: '0700'

- name: Add AWS Roles Anywhere profile to config
  ansible.builtin.blockinfile:
    path: "~{{ aws_backup_user }}/.aws/config"
    create: yes
    owner: "{{ aws_backup_user }}"
    group: "{{ aws_backup_group }}"
    mode: '0600'
    marker: "# {mark} ANSIBLE MANAGED BLOCK: AWS ROLES ANYWHERE"
    block: |
      [profile backups-profile]
      credential_process = /usr/local/bin/aws_signing_helper credential-process --certificate {{ aws_cert_path }}/aws-backup.crt --private-key {{ aws_key_path }}/aws-backup.key --intermediates {{ aws_cert_path }}/aws-backup-chain.pem --trust-anchor-arn {{ aws_trust_anchor_arn }} --profile-arn {{ aws_profile_arn }} --role-arn {{ aws_role_arn }}

- name: Create cron jobs for AWS S3 backups
  ansible.builtin.cron:
    name: "AWS Backup job: {{ item.key }}"
    minute: "{{ (item.value.minute | default('0') | int + 30) % 60 }}"
    hour: "{{ item.value.hour | default('2') }}"
    job: >
      /usr/local/bin/aws s3 sync {{ item.value.local_dir }} s3://{{ aws_backups_bucket }}/{{ item.key }}/
      --storage-class DEEP_ARCHIVE
      --profile backups-profile
      --only-show-errors
  loop: "{{ rsync_net_backup_jobs | dict2items }}"
