---

- name: Ensure cron is installed
  ansible.builtin.apt:
    name: cron
    state: present

- name: Configure backups to AWS
  ansible.builtin.include_tasks: aws.yml
  when: backups_aws_enabled | default(true) | bool

- name: Configure backups to rsync.net
  ansible.builtin.include_tasks: rsync_net.yml
