---

vault_ansible: "{{ lookup('community.hashi_vault.vault_kv2_get', 'all/ansible', engine_mount_point='infrastructure/ansible-playbooks/secrets')['secret'] }}"

ansible_ssh_user: "{{ vault_ansible['ssh_user'] }}"
