---

vault_acme: "{{ lookup('community.hashi_vault.vault_kv2_get', 'all/acme')['secret'] }}"
vault_ansible: "{{ lookup('community.hashi_vault.vault_kv2_get', 'all/ansible')['secret'] }}"
vault_cloudflare: "{{ lookup('community.hashi_vault.vault_kv2_get', 'all/cloudflare')['secret'] }}"
vault_prometheus_exporters_users: "{{ lookup('community.hashi_vault.vault_kv2_get', 'all/exporters/users')['secret'] }}"
vault_rsync_net: "{{ lookup('community.hashi_vault.vault_kv2_get', 'all/rsync_net')['secret'] }}"

ansible_ssh_user: "{{ vault_ansible['ssh_user'] }}"

domain: dylanw.net

gitlab_url: "https://gitlab.dylanw.dev"

acme_contact: "{{ vault_acme['contact_email'] }}"
acme_directory: https://acme-v02.api.letsencrypt.org/directory

cloudflare_api_token: "{{ vault_cloudflare['api_token'] }}"
cloudflare_account_id: "{{ vault_cloudflare['account_id'] }}"
cloudflare_zone_id: "{{ vault_cloudflare['zone_id'] }}"

node_exporter_basic_auth_users: "{{ vault_prometheus_exporters_users }}"
mysqld_exporter_basic_auth_users: "{{ vault_prometheus_exporters_users }}"

rsync_net_user: "{{ vault_rsync_net['user'] }}"
rsync_net_host: "{{ vault_rsync_net['host'] }}"
rsync_net_private_key: "{{ vault_rsync_net['private_key'] }}"
rsync_net_public_key: "{{ vault_rsync_net['public_key'] }}"
rsync_net_retention_days: 7
