---

- name: Create directory for Pelican
  ansible.builtin.file:
    path: /srv/www/dylanw.net/pelican
    state: directory

- name: Deploy Pelican Caddyfile
  ansible.builtin.template:
    src: pelican/Caddyfile.j2
    dest: /srv/www/dylanw.net/pelican/Caddyfile

- name: Deploy Pterodactyl Docker composition
  ansible.builtin.template:
    src: pelican/docker-compose.yml.j2
    dest: /srv/www/dylanw.net/pelican/docker-compose.yml

- name: Bring Docker containers up
  community.docker.docker_compose_v2:
    project_src: /srv/www/dylanw.net/pelican
