---

vault_mariadb_passwords: "{{ lookup('community.hashi_vault.vault_kv2_get', 'sql/mariadb/passwords')['secret'] }}"

dns_records:
  - zone: "{{ net_domain }}"
    record: sql
    type: CNAME
    value: "{{ ansible_host }}"

mariadb_passwords: "{{ vault_mariadb_passwords }}"

mariadb_users:
- name: antrim
  host: "web01.london.{{ net_domain }}"
- name: dylanw
  host: "web01.london.{{ net_domain }}"
- name: miners
  host: "web01.london.{{ net_domain }}"
- name: miners
  host: "game01.london.{{ net_domain }}"
- name: miners
  host: "game02.london.{{ net_domain }}"
- name: sqladm
  host: "desktop01.london.{{ net_domain }}"

mariadb_dbs:
- antrim_website
- dylanw_free-market-fandango-prod
- dylanw_halloween-voting-system-prod
- dylanw_initiative-tracker-prod
- dylanw_muckamore-credit-union-website-prod
- dylanw_utility-website-prod
- miners_panel
- miners_server
- miners_website
- muckam_website
