rsync_net_backup_jobs:
  gitlab_daily:
    hour: "02"
    minute: "00"
    local_dir: "/var/opt/gitlab/backups"
    command: "/opt/gitlab/bin/gitlab-backup create CRON=1"

gitlab_version: gitlab-ee=18.8.9-ee.0
