---

- name: Get IPv4 address
  ansible.builtin.uri:
    url: https://api.ipify.org?format=json
    return_content: true
  register: public_ipv4_address

- name: Create A record for host in DNS
  community.general.cloudflare_dns:
    zone: "{{ item.zone }}"
    record: "{{ item.record }}"
    type: "{{ item.type | default('A') }}"
    value: "{{ item.value | default(public_ipv4_address.json.ip) }}"
    solo: "{{ item.solo | default(True) }}"
    comment: Managed by Ansible
    api_token: "{{ cloudflare_api_token }}"
  loop: "{{ dns_records }}"

- name: Get IPv6 address
  ansible.builtin.uri:
    url: https://api6.ipify.org?format=json
    return_content: true
  register: public_ipv6_address

- name: Create AAAA record for host in DNS
  community.general.cloudflare_dns:
    zone: "{{ item.zone }}"
    record: "{{ item.record }}"
    type: AAAA
    value: "{{ public_ipv6_address.json.ip }}"
    solo: "{{ item.solo | default(True) }}"
    comment: Managed by Ansible
    api_token: "{{ cloudflare_api_token }}"
  loop: "{{ dns_records }}"
  when: item.type is undefined and item.value is undefined
