---

vault_wings_config: "{{ lookup('community.hashi_vault.vault_kv2_get', 'pterodactyl/wings/' + ansible_fqdn)['secret'] }}"
vault_pelican_wings_config: "{{ lookup('community.hashi_vault.vault_kv2_get', 'pelican/wings/' + ansible_fqdn)['secret'] }}"

wings_uuid: "{{ vault_wings_config['uuid'] }}"
wings_token_id: "{{ vault_wings_config['token_id'] }}"
wings_token: "{{ vault_wings_config['token'] }}"

pelican_wings_uuid: "{{ vault_pelican_wings_config['uuid'] }}"
pelican_wings_token_id: "{{ vault_pelican_wings_config['token_id'] }}"
pelican_wings_token: "{{ vault_pelican_wings_config['token'] }}"

backups_jobs:
  pterodactyl_daily:
    hour: "00"
    minute: "00"
    local_dir: "/var/lib/pterodactyl/backups"
