---

vault_wings_config: "{{ lookup('community.hashi_vault.vault_kv2_get', 'game/wings/' + inventory_hostname_short, engine_mount_point='secrets/infrastructure/ansible-playbooks')['secret'] }}"

wings_uuid: "{{ vault_wings_config['uuid'] }}"
wings_token_id: "{{ vault_wings_config['token_id'] }}"
wings_token: "{{ vault_wings_config['token'] }}"

backup_jobs:
  pterodactyl_daily:
    hour: "00"
    minute: "00"
    local_dir: "/var/lib/pterodactyl/backups"
