vault_mariadb_passwords: "{{ lookup('community.hashi_vault.vault_kv2_get', 'sql/mariadb/passwords')['secret'] }}"

mariadb_admin_host: sql.dylanw.net
mariadb_admin_user: sqladm
mariadb_admin_password: "{{ vault_mariadb_passwords[mariadb_admin_user] }}"
