---

- hosts: desktop
  pre_tasks:
    - name: Ensure gnupg is installed
      ansible.builtin.apt:
        name: gnupg
        state: present
        update_cache: yes
      become: yes

    - name: Download and dearmor HashiCorp GPG key
      ansible.builtin.shell:
        cmd: curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
      become: yes

    - name: Add HashiCorp apt repository
      ansible.builtin.apt_repository:
        filename: hashicorp
        # Note the change from .asc to .gpg here
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
      become: yes
      
    - name: Install system packages and development dependencies
      ansible.builtin.package:
        name:
          # Common utilities
          - zsh
          - rsync
          - rclone
          - mariadb-client
          - vault
          - zip
          - unzip
          - tmux
          - curl
          - git

          # Ansible
          - sshpass
        state: present
        update_cache: yes
      become: yes
  roles:
  - role: aws
  - role: geerlingguy.docker
    become: yes
  post_tasks:
    - name: Create user account for dylan
      ansible.builtin.user:
        name: dylan
        comment: Dylan Wilson
        shell: /usr/bin/zsh
      become: yes

    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add dylan user to docker group
      ansible.builtin.user:
        name: dylan
        groups: docker
        append: yes
      become: yes

    - name: Configure .my.cnf for dylan
      ansible.builtin.copy:
        content: |
          [client]
          host={{ maraidb_admin_host }}
          user={{ mariadb_admin_user }}
          password='{{ mariadb_admin_password }}'
        dest: /home/dylan/.my.cnf
        owner: dylan
        group: dylan
        mode: '0600'
      become: yes
