---

- hosts: desktop
  pre_tasks:
    - name: Ensure gnupg is installed
      ansible.builtin.apt:
        name: gnupg
        state: present
        update_cache: yes
      become: yes

    - name: Download and dearmor HashiCorp GPG key
      ansible.builtin.shell:
        cmd: curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
      become: yes

    - name: Add HashiCorp apt repository
      ansible.builtin.apt_repository:
        filename: hashicorp
        # Note the change from .asc to .gpg here
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
      become: yes
      
    - name: Install system packages and development dependencies
      ansible.builtin.package:
        name:
          # Common utilities
          - zsh
          - rsync
          - rclone
          - mariadb-client
          - vault
          - zip
          - unzip
          - tmux
          - curl
          - git
          - jq

          # Ansible
          - sshpass
        state: present
        update_cache: yes
      become: yes
  roles:
  - role: aws
  - role: geerlingguy.docker
    become: yes
  post_tasks:
    - name: Allow unprivileged user namespaces (Required for Debian)
      ansible.posix.sysctl:
        name: kernel.unprivileged_userns_clone
        value: '1'
        state: present
        reload: yes
      become: yes

    - name: Ensure dependencies for Rootless Docker are installed
      ansible.builtin.package:
        name:
          - dbus-user-session
          - slirp4netns
          - fuse-overlayfs
          - uidmap
          - docker-ce-rootless-extras
        state: present
      become: yes

    - name: Create user account for dylan
      ansible.builtin.user:
        name: dylan
        comment: Dylan Wilson
        shell: /usr/bin/zsh
      become: yes

    - name: Fetch dylan's user info
      ansible.builtin.getent:
        database: passwd
        key: dylan

    - name: Enable lingering for dylan
      ansible.builtin.command: "loginctl enable-linger dylan"
      args:
        creates: "/var/lib/systemd/linger/dylan"
      become: yes

    - name: Ensure ACL package is installed for unprivileged become
      ansible.builtin.package:
        name: acl
        state: present
      become: yes

    - name: Install Rootless Docker for dylan
      ansible.builtin.shell:
        cmd: "dockerd-rootless-setuptool.sh install"
      become: yes
      become_user: dylan
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd['dylan'][1] }}"
      args:
        creates: "/home/dylan/.config/systemd/user/docker.service"

    - name: Ensure Docker user service is started and enabled
      ansible.builtin.systemd:
        name: docker
        scope: user
        enabled: yes
        state: started
      become: yes
      become_user: dylan
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd['dylan'][1] }}"

    - name: Configure .my.cnf for dylan
      ansible.builtin.copy:
        content: |
          [client]
          host={{ mariadb_admin_host }}
          user={{ mariadb_admin_user }}
          password='{{ mariadb_admin_password }}'
        dest: /home/dylan/.my.cnf
        owner: dylan
        group: dylan
        mode: '0600'
      become: yes
