---

- hosts: desktop
  pre_tasks:
    - name: Install HashiCorp GPG key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
        mode: '0644'
      become: yes

    - name: Add HashiCorp apt repository
      ansible.builtin.apt_repository:
        filename: hashicorp
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
      become: yes

    - name: Install system packages and development dependencies
      ansible.builtin.package:
        name:
          - zsh
          - rsync
          - rclone
          - mariadb-client
          - vault
          - zip
          - unzip

          # For asdf Python
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - curl
          - git
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev

          # Ansible
          - sshpass

          # https://www.jetbrains.com/help/pycharm/2025.1/set-up-GPG-commit-signing.html
          - gnupg2
          - gnupg-agent
          - pinentry-gnome3
        state: present
        update_cache: yes
      become: yes
  roles:
  - role: aws
  - role: geerlingguy.docker
    become: yes
  post_tasks:
    - name: Create user account for dylan
      ansible.builtin.user:
        name: dylan
        comment: Dylan Wilson
        shell: /usr/bin/zsh
      become: yes

    - name: Configure SSH authorized keys for dylan
      ansible.posix.authorized_key:
        user: dylan
        state: present
        key: "{{ item }}"
      become: yes
      loop:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyJ88mt6hyT+Lxk9HD2B2hIyz8orzJJsoTAXNVQuYxTeQYZwJ2wnsK9+k4eD6/Q3/7f1cE6pG4cF/x8P5/xnw5KlCP+ENf4VfnjPOOF7gafJxsB5ECmZuhyWgjbKFt6J+ANTvEVVDWjgV4K5+s0KyZujK9gV2B4WW31ThqS7EIByH3lAu/o+nQd3Sptra5LlCs01/YxcWdPltmvGuyW5a770bAc/F83qjgNmdLGCAx8Dxx9jLLUjW6LxWWql593CCp6ZGIlk/3qmsxbT2E5EN0xAFgUiomFUFBY2mC+ED1gHBH9bP0MnUleFJ8ddbO96/1mr1h5RWUvbdj//wLaCevZ90o8N2+7j4X7RI1td2iePzowq+o5sO+klbEa+w4SDfKtXYrf6FtUbuXGQD+iL8OIVyTGVDSzQqVr2EPZLNqNLRcTIH4ZkzsXuDHexirA4b+rRGRXIrlQOtkO58U9NrvWthp0oCOx35I+GfW7y+pyS6Bljg9LlWFjUSulmSmF1U= dylan@desktop01
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGR054Pp32qm3CQOFPfaYf5DftOQDnLG0vc/YKubEra/ dwils@desktop01

    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add dylan user to docker group
      ansible.builtin.user:
        name: dylan
        groups: docker
        append: yes
      become: yes
