---

- hosts: git
  roles:
    - role: dns
    - role: acme
      become: yes
      vars:
        acme_certs:
          "pages.{{ dev_domain }}":
            cloudflare_zone: "{{ dev_domain }}"
            alternative_domains:
              - "*.pages.{{ dev_domain }}"
    - role: gitlab
      become: yes
    - role: backups
      become: yes
  handlers:
    - name: Reconfigure GitLab after certificates changed
      become: yes
      ansible.builtin.command: gitlab-ctl reconfigure
      listen: acme_certs_changed
