---

- hosts: mail
  pre_tasks:
  - name: Install jq which is required by the mailcow update script
    ansible.builtin.package:
      name:
      - jq
      state: present
      update_cache: yes
    become: yes
  - name: Ensure backup directory exists
    ansible.builtin.file:
      path: "/var/backups/mailcow"
      state: directory
      owner: root
      group: root
      mode: '0775'
    become: yes
  roles:
  - role: dns
  - role: geerlingguy.docker
    become: yes
    vars:
      docker_install_compose_plugin: false
      docker_install_compose: true
  - role: mailcow.mailcow
    become: yes
    vars:
      mailcow__hostname: "{{ mail_hostname }}"
  - role: backups
    become: yes