---

dns_records:
  - zone: "{{ prometheus_zone }}"
    record: "{{ prometheus_hostname }}"
    type: CNAME
    value: "{{ ansible_host }}"
  - zone: "{{ grafana_zone }}"
    record: "{{ grafana_hostname }}"
    type: CNAME
    value: "{{ ansible_host }}"
