---

- name: Configure Proxmox local storage allowed content types
  community.proxmox.proxmox_storage:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_token_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    nodes:
      - "{{ proxmox_host }}"
    name: local
    type: dir
    dir_options:
      path: /var/lib/vz
    content:
      - vztmpl
      - images
      - iso
      - backup
      - snippets
    state: present

- name: Add NFS storage to Proxmox VE Cluster
  community.proxmox.proxmox_storage:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_token_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    nodes:
    - "{{ proxmox_host }}"
    name: "{{ item.server }}"
    type: nfs
    nfs_options:
      server: "{{ item.server }}"
      export: "{{ item.export }}"
    content:
    - backup
    state: present
  loop: "{{ nfs_mounts }}"
