---

- name: Configure Proxmox local storage allowed content types
  ansible.builtin.command: pvesh set /storage/local --content vztmpl,images,iso,backup,snippets

- name: Add NFS storage to Proxmox VE Cluster
  community.proxmox.proxmox_storage:
    api_host: "{{ item.props.host }}"
    api_user: "{{ proxmox_token_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    nodes:
    - "{{ proxmox_host }}"
    name: "{{ item.props.server }}"
    type: nfs
    nfs_options:
      server: "{{ item.props.server }}"
      export: "{{ item.props.export }}"
    content:
    - backup
    state: present
    loop: "{{ nfs_mounts }}"
